export const purple = [
    {
      img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/03-7.jpg",
      name:"OCHENA MON",
      date:"12 April 2016",
      lyrics:"Handibam",
      music:"Robarto Marlin",
      bass:"Jabed ali",
      guiders:"Monali",
      drumbs:"Johan Malik",
      Vocals:"Paul Hanri",
    },
    {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/06-2.jpg",
        name:"PNEORA CAHY",
        date:"15 June 2016",
        lyrics:"Handibam",
      music:"Robarto Marlin",
      bass:"Jabed ali",
      guiders:"Monali",
      drumbs:"Johan Malik",
      Vocals:"Paul Hanri",
      },
      {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/Music_Album_03.jpg",
        name:"AROMA CAHY",
        date:"12 April 2016",
        lyrics:"Handibam",
      music:"Robarto Marlin",
      bass:"Jabed ali",
      guiders:"Monali",
      drumbs:"Johan Malik",
      Vocals:"Paul Hanri",
      },
      {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/Music_Album_02.jpg",
        name:"JNOIBO AHADRE",
        date:"12 April 2016",
        lyrics:"Handibam",
      music:"Robarto Marlin",
      bass:"Jabed ali",
      guiders:"Monali",
      drumbs:"Johan Malik",
      Vocals:"Paul Hanri",
      },
      {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/03-7.jpg",
        name:"PYARI TUMI",
        date:"12 April 2016",
        lyrics:"Handibam",
      music:"Robarto Marlin",
      bass:"Jabed ali",
      guiders:"Monali",
      drumbs:"Johan Malik",
      Vocals:"Paul Hanri",
      },
  ]