export const event = [
    {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2018/04/Galry_img_03-128x116.jpg",
        title:"JHINGJOG MUSIC HOUR",
        location:"Chandarpur,California USA",
        date:"27 February,2022",
        time:"8:00PM",
        price:"$29",
        heading:"Collaborative negotiate next-generation web-readiness rather than market driven data. Uniquely disseminate client centered alignments.",
        evntdetail:"Collaborative negotiate next-generation web-readiness rather than market driven data. Continually incubate synergistic meta-services before outsourcing. Proactive synthesize dynamic web services vis installed base products. Holisticly disseminate proactive networks without user friendly technologies. Uniquely disseminate client centered alignments with economically sound human capital,Competent customize B2B collaboration and idea-sharing whereas process centric benefits. Authoritative productize intermandated solutions whereas next-generation methods of empowerment. Continually simplify cutting-edge content vis-a-vis cross unit networks. Credibly optimize low-risk. Proactive synthesize dynamic web services vis installed base products.",
        perfomer1:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/04-1.jpg",
        perfomer2:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/03-3.jpg",
        perfomer3:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/02-4.jpg",
        perfomer4:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/01-7.jpg",
        map:"../map.jpeg",
        bus:"2km",
        rail:"5km",
        airport:"10km",
        hotel:"1km",
        restaurant:"0.5km",
        
    },
    {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2018/04/Galry_img_03-128x116.jpg",
        title:"JHINGJOG MUSIC HOUR",
        location:"Chandarpur,California USA",
        date:"27 February,2022",
        time:"8:00PM",
        price:"$29",
        heading:"Collaborative negotiate next-generation web-readiness rather than market driven data. Uniquely disseminate client centered alignments.",
        evntdetail:"Collaborative negotiate next-generation web-readiness rather than market driven data. Continually incubate synergistic meta-services before outsourcing. Proactive synthesize dynamic web services vis installed base products. Holisticly disseminate proactive networks without user friendly technologies. Uniquely disseminate client centered alignments with economically sound human capital,Competent customize B2B collaboration and idea-sharing whereas process centric benefits. Authoritative productize intermandated solutions whereas next-generation methods of empowerment. Continually simplify cutting-edge content vis-a-vis cross unit networks. Credibly optimize low-risk. Proactive synthesize dynamic web services vis installed base products.",
        perfomer1:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/04-1.jpg",
        perfomer2:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/03-3.jpg",
        perfomer3:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/02-4.jpg",
        perfomer4:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/01-7.jpg",
        map:"../map.jpeg",
        bus:"2km",
        rail:"5km",
        airport:"10km",
        hotel:"1km",
        restaurant:"0.5km",
        
    },
    {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2018/04/Galry_img_03-128x116.jpg",
        title:"JHINGJOG MUSIC HOUR",
        location:"Chandarpur,California USA",
        date:"27 February,2022",
        time:"8:00PM",
        price:"$29",
        heading:"Collaborative negotiate next-generation web-readiness rather than market driven data. Uniquely disseminate client centered alignments.",
        evntdetail:"Collaborative negotiate next-generation web-readiness rather than market driven data. Continually incubate synergistic meta-services before outsourcing. Proactive synthesize dynamic web services vis installed base products. Holisticly disseminate proactive networks without user friendly technologies. Uniquely disseminate client centered alignments with economically sound human capital,Competent customize B2B collaboration and idea-sharing whereas process centric benefits. Authoritative productize intermandated solutions whereas next-generation methods of empowerment. Continually simplify cutting-edge content vis-a-vis cross unit networks. Credibly optimize low-risk. Proactive synthesize dynamic web services vis installed base products.",
        perfomer1:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/04-1.jpg",
        perfomer2:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/03-3.jpg",
        perfomer3:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/02-4.jpg",
        perfomer4:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/01-7.jpg",
        map:"../map.jpeg",
        bus:"2km",
        rail:"5km",
        airport:"10km",
        hotel:"1km",
        restaurant:"0.5km",
        
    },
    {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2018/04/Galry_img_03-128x116.jpg",
        title:"JHINGJOG MUSIC HOUR",
        location:"Chandarpur,California USA",
        date:"27 February,2022",
        time:"8:00PM",
        price:"$29",
        heading:"Collaborative negotiate next-generation web-readiness rather than market driven data. Uniquely disseminate client centered alignments.",
        evntdetail:"Collaborative negotiate next-generation web-readiness rather than market driven data. Continually incubate synergistic meta-services before outsourcing. Proactive synthesize dynamic web services vis installed base products. Holisticly disseminate proactive networks without user friendly technologies. Uniquely disseminate client centered alignments with economically sound human capital,Competent customize B2B collaboration and idea-sharing whereas process centric benefits. Authoritative productize intermandated solutions whereas next-generation methods of empowerment. Continually simplify cutting-edge content vis-a-vis cross unit networks. Credibly optimize low-risk. Proactive synthesize dynamic web services vis installed base products.",
        perfomer1:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/04-1.jpg",
        perfomer2:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/03-3.jpg",
        perfomer3:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/02-4.jpg",
        perfomer4:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/01-7.jpg",
        map:"../map.jpeg",
        bus:"2km",
        rail:"5km",
        airport:"10km",
        hotel:"1km",
        restaurant:"0.5km",
        
    },
    {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2018/04/Galry_img_03-128x116.jpg",
        title:"JHINGJOG MUSIC HOUR",
        location:"Chandarpur,California USA",
        date:"27 February,2022",
        time:"8:00PM",
        price:"$29",
        heading:"Collaborative negotiate next-generation web-readiness rather than market driven data. Uniquely disseminate client centered alignments.",
        evntdetail:"Collaborative negotiate next-generation web-readiness rather than market driven data. Continually incubate synergistic meta-services before outsourcing. Proactive synthesize dynamic web services vis installed base products. Holisticly disseminate proactive networks without user friendly technologies. Uniquely disseminate client centered alignments with economically sound human capital,Competent customize B2B collaboration and idea-sharing whereas process centric benefits. Authoritative productize intermandated solutions whereas next-generation methods of empowerment. Continually simplify cutting-edge content vis-a-vis cross unit networks. Credibly optimize low-risk. Proactive synthesize dynamic web services vis installed base products.",
        perfomer1:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/04-1.jpg",
        perfomer2:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/03-3.jpg",
        perfomer3:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/02-4.jpg",
        perfomer4:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/01-7.jpg",
        map:"../map.jpeg",
        bus:"2km",
        rail:"5km",
        airport:"10km",
        hotel:"1km",
        restaurant:"0.5km",
        
    },
]