export const recent = [
    {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/Blog_01-374x230.jpg",
        title:"The Summer Music Tour 1999 in USA",
        desc:"Posted by antmadmin on January 17,2017",
        para:"Credibly impact covalent content whereas superior niche markets. Dynamically productize economically sound results vis-a-vis ethical markets. Globally architect installed base technologies through standardized intellectual capital. Phosfluorescently utilize extensive scenarios whereas value-added intellectual capital. Phosfluorescently visualize standards compliant platforms vis-a-vis accurate benefits.Continually evisculate just in time strategic theme areas for quality methodologies. Authoritatively embrace real-time processes with stand-alone quality vectors. Distinctively predominate high-payoff mindshare without orthogonal action items. Progressively formulate unique e-tailers rather than enabled technology. Competently predominate long-term high-impact meta-services through backend convergence.Globally generate vertical systems with distributed data. Seamlessly streamline global web-readiness without interdependent results. Continually promote cross-unit communities through fully tested methods of empowerment. Globally envisioneer world-class total linkage for goal-oriented bandwidth. Professionally pursue cross functional web-readiness with long-term high-impact e-business.Holisticly reintermediate adaptive opportunities through revolutionary e-markets. Dynamically benchmark next-generation sources through competitive models. Conveniently enable state of the art infomediaries with enterprise imperatives. Progressively aggregate ubiquitous strategic theme areas via user-centric partnerships. Globally reconceptualize go forward portals after multimedia based potentialities."
    },
    {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/Blog_04-374x230.jpg",
        title:"The Summer Music Tour 1999 in USA",
        desc:"Posted by antmadmin on January 17,2017",
        para:"Credibly impact covalent content whereas superior niche markets. Dynamically productize economically sound results vis-a-vis ethical markets. Globally architect installed base technologies through standardized intellectual capital. Phosfluorescently utilize extensive scenarios whereas value-added intellectual capital. Phosfluorescently visualize standards compliant platforms vis-a-vis accurate benefits.Continually evisculate just in time strategic theme areas for quality methodologies. Authoritatively embrace real-time processes with stand-alone quality vectors. Distinctively predominate high-payoff mindshare without orthogonal action items. Progressively formulate unique e-tailers rather than enabled technology. Competently predominate long-term high-impact meta-services through backend convergence.Globally generate vertical systems with distributed data. Seamlessly streamline global web-readiness without interdependent results. Continually promote cross-unit communities through fully tested methods of empowerment. Globally envisioneer world-class total linkage for goal-oriented bandwidth. Professionally pursue cross functional web-readiness with long-term high-impact e-business.Holisticly reintermediate adaptive opportunities through revolutionary e-markets. Dynamically benchmark next-generation sources through competitive models. Conveniently enable state of the art infomediaries with enterprise imperatives. Progressively aggregate ubiquitous strategic theme areas via user-centric partnerships. Globally reconceptualize go forward portals after multimedia based potentialities."
    },
    {
        img:"http://demos.codexcoder.com/anthem/wp-content/uploads/2017/05/Blog_03-374x230.jpg",
        title:"The Summer Music Tour 1999 in USA",
        desc:"Posted by antmadmin on January 17,2017",
        para:"Credibly impact covalent content whereas superior niche markets. Dynamically productize economically sound results vis-a-vis ethical markets. Globally architect installed base technologies through standardized intellectual capital. Phosfluorescently utilize extensive scenarios whereas value-added intellectual capital. Phosfluorescently visualize standards compliant platforms vis-a-vis accurate benefits.Continually evisculate just in time strategic theme areas for quality methodologies. Authoritatively embrace real-time processes with stand-alone quality vectors. Distinctively predominate high-payoff mindshare without orthogonal action items. Progressively formulate unique e-tailers rather than enabled technology. Competently predominate long-term high-impact meta-services through backend convergence.Globally generate vertical systems with distributed data. Seamlessly streamline global web-readiness without interdependent results. Continually promote cross-unit communities through fully tested methods of empowerment. Globally envisioneer world-class total linkage for goal-oriented bandwidth. Professionally pursue cross functional web-readiness with long-term high-impact e-business.Holisticly reintermediate adaptive opportunities through revolutionary e-markets. Dynamically benchmark next-generation sources through competitive models. Conveniently enable state of the art infomediaries with enterprise imperatives. Progressively aggregate ubiquitous strategic theme areas via user-centric partnerships. Globally reconceptualize go forward portals after multimedia based potentialities."
    },
]